# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/freebsd-qt6.yml
      # The Linux runners are based on Suse which doesn't currently ship aws-sdk-cpp.
      # - /gitlab-templates/linux.yml
      # We need to have linux-qt6 built to have the documentation
      #- /gitlab-templates/documentation.yml
